name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2 # Updated to latest major version
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install Node dependencies
        run: npm ci
      - name: Build Inertia/react
        run: npm run build --if-present
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Migrations and Seed Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
      - name: Create /tmp/deploy directory
        run: mkdir -p /tmp/deploy
      - name: Deploy to cPanel
        env:
          CPANELUSER: ${{ secrets.CPANELUSER }}
          CPANELDOMAIN: ${{ secrets.CPANELDOMAIN }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy
          rsync -avz --exclude-from=.rsyncignore  "ssh -p 64000 -i /tmp/deploy_key -o StrictHostKeyChecking=no" ./ $CPANELUSER@$CPANELDOMAIN:public_html
